### ISSUE TITLE
Indexing curated Label and summary for free text search

### ISSUE THREAD

**Issue by DiaZork** [ec-doris/kohesio-backend#232]
As we are adding this label we need to be able to have the user find the project using it…

- Label [P581563](https://linkedopendata.eu/prop/direct/P581563) 
- Summary [P581562](https://linkedopendata.eu/prop/direct/P581562)

**Comment by madewild** [comment]
Related to #238

**Comment by madewild** [comment]
Apart from the fact that https://linkedopendata.eu/prop/direct/P581563 throws a 404 (reported to @svili), are the curated labels and summaries correctly indexed now? @D063520 @DiaZork can we close this?

**Comment by D063520** [comment]
the 404, is due to a missing redirect. On other installations we generally have an nginx server sitting in front. But could not convince the admins yet to put this in place.

The two properties are indexed. In fact everything that is attached to the entity is indexed, since they query is:

mdlc:luceneReindexQuery "SELECT ?s ?p ?o WHERE { ?s <https://linkedopendata.eu/prop/direct/P35> <https://linkedopendata.eu/entity/Q9934> ; ?p ?o . FILTER(LANG(?o) = 'en')}  ";
