### ISSUE TITLE
Entity QID returned as NUTS for projects without NUTS on dev endpoint

### ISSUE THREAD

**Issue by svili** [ec-doris/kohesio-backend#246]
Querying for an operation's P1845 (contained in NUTS) returns the operations QID instead of null, if the operation has no P1845 statement. This only occurs while querying on the endpoint on the cluster, the query console is fine.

E.g. for an operation without P1845 [like this one](https://linkedopendata.eu/wiki/Item:Q3088836) the result is the entity QID instead of null.
```
PREFIX wd: <https://linkedopendata.eu/entity/>
PREFIX wdt: <https://linkedopendata.eu/prop/direct/>
SELECT ?operation ?nuts
WHERE {
  VALUES ?operation {
      wd:Q3088836
  }
  OPTIONAL { ?operation wdt:P1845 ?nuts. }
}
```

**Comment by D063520** [comment]
Good catch. Basically we are attaching all nuts hierarchy in the endpoint cluster to the project. The reason is that we need this to query faster. The query goes like:

`time curl -G 'http://localhost:1234/api/endpoint/sparql' --data-urlencode 'update= I
NSERT {?s0 <https://linkedopendata.eu/prop/direct/P1845>  ?nut} where {  
  ?s0 <https://linkedopendata.eu/prop/direct/P1845>* ?nut .  
  ?s0 <https://linkedopendata.eu/prop/direct/P35> <https://linkedopendata.eu/entity/Q9934> . 
}  '  -H 'timeout: 1600' -H 'accept: application/sparql-results+json'`

The problem here is the *. This means "ZeroOrMorePath" it should be changed to + "OneOrMorePath". Besides the fact that you are right, I should change this .... is this causing any problems to you?

**Comment by svili** [comment]
Not anymore, no, so no rush.

**Comment by madewild** [comment]
@D063520 what's the status of this?

**Comment by D063520** [comment]
this is changed
