### ISSUE TITLE
React EU filter not working

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#261]
https://kohesio.ec.europa.eu/en/projects?theme=React-EU is showing no results
@Dgojsic is it normal? Should we hide this theme on https://kohesio.ec.europa.eu/en/themes?

**Comment by madewild** [comment]
@DiaZork https://kohesio.ec.europa.eu/api/projects?offset=0&limit=15&theme=https://linkedopendata.eu/wiki/Item:Q4410815&language=en is not finding any project

**Comment by Dgojsic** [comment]
We should definately adapt to make the filter work. However I am not sure why the behavior is as described, because in principle all thematic objectives are dervied from the intervention field anyways. @svili Do you remember when you and Roberto added the REACT projects doing it in a different way than before?

**Comment by DiaZork** [comment]
I fixed the backend for this then. It's on dev and test right now.
But as I changed the query, the cache is not calculated yet so be aware that it might be slow when you tried it the first time (except if someone else did it before you)
