### ISSUE TITLE
Excel export is limited to 100 lines

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#264]
https://kohesio.development.ec.europa.eu/en/projects?keywords=eurovelo has 112 projects but only 100 get exported

**Comment by DiaZork** [comment]
There was a limit of 100 projects when using keyword that was removed but there is this strange behavior of random number of result that happen only with the csv export. 
This problem is only when we call 
http://kohesio.development.ec.europa.eu/api/projects/download/csv?keywords=eurovelo&language=en
with this API call it work
http://kohesio.development.ec.europa.eu/wikibase/facet/eu/search/project/csv?language=en&keywords=eurovelo&limit=1000&offset=0
while the 2 should do the same thing
 
So my guess is that the problem come from the BFF or the network between some service that cut the connection before the file is fully transferred (knowing that the cut does look random when the file is not full so it might be something like that)

**Comment by madewild** [comment]
All 112 projects are exported now
