### ISSUE TITLE
Missing beneficiaries in exports

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio-backend#41]
https://linkedopendata.eu/wiki/Item:Q2510730 is missing from Polish beneficiary export

https://query.linkedopendata.eu/#SELECT%20distinct%20%3Fbeneficiary%20WHERE%20%7B%20%3Fbeneficiary%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ196899%3E%20.%20%3Fbeneficiary%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP32%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ13%3E%20.%20%7D

is not finding it !!

**Comment by D063520** [comment]
basically it is the rank of the statement ....
it is beneficiary with "normal rank" and research institute with "high rank"!
oh no!!!!!!!!
why is knwoledge representation sometimes so tideus!

SOLUTION: make all beneficiaries of high rank, instead of normal rank ....

**Comment by D063520** [comment]
Query non reefined:

https://query.linkedopendata.eu/#select%20%28count%28%2a%29%20as%20%3Fc%29%20where%20%7B%0A%20%3Fs1%20%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ196899%3E%20.%0A%7D

no matching all beneficiaries since some have preferred rank higher than normal. The query matching all is:

https://query.linkedopendata.eu/#select%20%28count%28%2a%29%20as%20%3Fc%29%20where%20%7B%0A%20%3Fs1%20%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2FP35%3E%20%20%3Fblank%20.%0A%20%3Fblank%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fstatement%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ196899%3E%0A%7D

**Comment by D063520** [comment]
Query non reefined:

https://query.linkedopendata.eu/#select%20%28count%28%2a%29%20as%20%3Fc%29%20where%20%7B%0A%20%3Fs1%20%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fdirect%2FP35%3E%20%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ196899%3E%20.%0A%7D

no matching all beneficiaries since some have preferred rank higher than normal. The query matching all is:

https://query.linkedopendata.eu/#select%20%28count%28%2a%29%20as%20%3Fc%29%20where%20%7B%0A%20%3Fs1%20%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2FP35%3E%20%20%3Fblank%20.%0A%20%3Fblank%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fprop%2Fstatement%2FP35%3E%20%3Chttps%3A%2F%2Flinkedopendata.eu%2Fentity%2FQ196899%3E%0A%7D

**Comment by D063520** [comment]
Some code. Remove instance of beneficiary statement. Something like this:

 claimsToRemove = []
    for wikibase_claims in wikibase_item.claims:
        for wikibase_c in wikibase_item.claims.get(wikibase_claims):
            if wikibase_c.toJSON().get('mainsnak').get('property') == "P889":
                claimsToRemove.append(wikibase_c)
    if len(claimsToRemove) > 0:
        wikibase_item.removeClaims(claimsToRemove)

Add the statement again with high rank, something like:


 claim = pywikibot.Claim(wikibase_repo, "P35", datatype='wikibase-item')
                        object = pywikibot.ItemPage(wikibase_repo, "Q9934")
                        claim.setTarget(object)
                        newClaims.append(claim.toJSON())
 claim.setRank("preferred")

**Comment by D063520** [comment]
The numbers are now matching ...
